# Generated by Django 5.0.3 on 2024-03-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('published_timestamp', models.DateTimeField()),
                ('subject', models.CharField(max_length=50)),
            ],
        ),
    ]
